name: Solicitud de funcionalidad
description: Solicita una nueva funcionalidad o mejora para la aplicaci贸n
title: '[Feature] '
labels: [feature]
assignees: []
# projects: [ArditecSistemas/4]
type: 'Feature'

body:
  - type: markdown
    attributes:
      value: '## 隆Bienvenido! '
  - type: markdown
    attributes:
      value: |
        Tienes una idea que te gustaria ver implementada en la aplicaci贸n? 隆Ayudanos a mejorar! 
  - type: textarea
    id: description
    attributes:
      label: Descripci贸n
      description: 驴Qu茅 funcionalidad o mejora te gustaria implementar? Incluye todo el contexto e informaci贸n que puedas proporcionar.
      placeholder: 'Me gustar铆a que ...'
    validations:
      required: true
