name: Solicitud de funcionalidad
description: Tienes una idea que te gustaria ver implementada en la aplicación? ¡Ayúdanos a mejorar! 🚀
title: '[Feature] '
labels: [feature]
assignees: []
# projects: [ArditecSistemas/4]
type: 'Feature'

body:
  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: ¿Qué funcionalidad o mejora te gustaria implementar? Incluye todo el contexto e información que puedas proporcionar.
      placeholder: 'Me gustaría que ...'
    validations:
      required: true
